package MeteoApp;


/**
* MeteoApp/Meteo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Meteo.idl
* lundi 12 février 2018 à 13:42:04 heure normale d’Europe centrale
*/

public interface Meteo extends MeteoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Meteo
