package MeteoApp;


/**
* MeteoApp/MeteoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Meteo.idl
* lundi 12 février 2018 à 13:42:04 heure normale d’Europe centrale
*/

public interface MeteoOperations 
{
  String afficherBulletincourant ();
} // interface MeteoOperations
