package MeteoApp;

/**
* MeteoApp/MeteoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Meteo.idl
* lundi 12 février 2018 à 13:42:04 heure normale d’Europe centrale
*/

public final class MeteoHolder implements org.omg.CORBA.portable.Streamable
{
  public MeteoApp.Meteo value = null;

  public MeteoHolder ()
  {
  }

  public MeteoHolder (MeteoApp.Meteo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MeteoApp.MeteoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MeteoApp.MeteoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MeteoApp.MeteoHelper.type ();
  }

}
