package MeteoApp;


/**
* MeteoApp/MeteoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Meteo.idl
* lundi 12 février 2018 à 13:42:04 heure normale d’Europe centrale
*/

public abstract class MeteoPOA extends org.omg.PortableServer.Servant
 implements MeteoApp.MeteoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("afficherBulletincourant", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MeteoApp/Meteo/afficherBulletincourant
       {
         String $result = null;
         $result = this.afficherBulletincourant ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MeteoApp/Meteo:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Meteo _this() 
  {
    return MeteoHelper.narrow(
    super._this_object());
  }

  public Meteo _this(org.omg.CORBA.ORB orb) 
  {
    return MeteoHelper.narrow(
    super._this_object(orb));
  }


} // class MeteoPOA
